name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: brew install
        run: brew install xcodegen
      - name: make
        run: make -C src clean all
